version: '3.8'
services:
    mongo:
        image: mongo:latest
        container_name: mongodb
        restart: always
        ports:
            - "27017:27017"
        environment:
            #- MONGO_INITDB_DATABASE=KemGRES
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=mongo
        networks:
            - mongo_network
            
networks:
    mongo_network: