#docker-compose -f docker-compose_grafana.yml up -d

version: '3'

services:
  grafana:
    image: grafana/grafana:9.4.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=agenty-flowcharting-panel

volumes:
  grafana_data:
