version: '3.6'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'  # Замените на ваш домен или IP
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'  # Замените на ваш домен или IP
        gitlab_rails['time_zone'] = 'UTC'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222  # Порт для SSH (по умолчанию 22 может быть занят)
        postgresql['enable'] = false
        redis['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'unicode'
        gitlab_rails['db_host'] = 'postgresql'
        gitlab_rails['db_database'] = 'gitlab'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'securepassword'  # Замените на надежный пароль
        gitlab_rails['redis_host'] = 'redis'
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: postgres:13
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: securepassword  # Замените на надежный пароль
      POSTGRES_DB: gitlab
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  postgresql_data:
  redis_data:
